import type { NewVenue } from '@/db/schema'

type SeedVenue = Omit<NewVenue, 'createdAt' | 'updatedAt'>

export const SEED_VENUES: SeedVenue[] = [
  // ── FINE DINING ────────────────────────────────────────────────────
  {
    id: 1,
    name: 'The Penrose Room',
    slug: 'the-penrose-room',
    description:
      "Colorado's only AAA Five Diamond restaurant, perched atop The Broadmoor resort with panoramic views of Cheyenne Lake and the Rocky Mountains. The Penrose Room offers an unparalleled fine dining experience with impeccable tableside service, an award-winning wine list, and a menu celebrating modern American cuisine with European influences. Jackets required; reservations essential.",
    shortDescription:
      "Colorado's only AAA Five Diamond restaurant, high atop The Broadmoor with breathtaking mountain views.",
    category: 'fine-dining',
    cuisine: 'american',
    neighborhood: 'broadmoor',
    address: '1 Lake Ave, Colorado Springs, CO 80906',
    phone: '7196347711',
    website: 'https://www.broadmoor.com/dining/penrose-room',
    priceRange: 4,
    hours: 'Tue–Sat 6:00 PM – 9:00 PM',
    features: JSON.stringify({ reservations: true, dressCode: true, views: true, specialOccasion: true }),
    featured: true,
    active: true,
    tier: 'free',
    displayOrder: 1,
  },
  {
    id: 2,
    name: 'Summit at The Broadmoor',
    slug: 'summit-broadmoor',
    description:
      'Summit is The Broadmoor\'s signature restaurant offering elevated American cuisine in a sophisticated mountain-lodge setting. The menu showcases the finest Colorado-sourced ingredients, from prime dry-aged steaks to fresh seafood flown in daily. The wine cellar holds over 15,000 bottles and the sommelier team is ready to guide your selection.',
    shortDescription:
      "The Broadmoor's premier steakhouse featuring Colorado-sourced ingredients and an exceptional wine program.",
    category: 'fine-dining',
    cuisine: 'american',
    neighborhood: 'broadmoor',
    address: '1 Lake Ave, Colorado Springs, CO 80906',
    phone: '7196347711',
    website: 'https://www.broadmoor.com/dining/summit',
    priceRange: 4,
    hours: 'Daily 5:30 PM – 10:00 PM',
    features: JSON.stringify({ reservations: true, dressCode: true, privatedining: true }),
    featured: true,
    active: true,
    tier: 'free',
    displayOrder: 2,
  },
  {
    id: 3,
    name: 'Ristorante del Lago',
    slug: 'ristorante-del-lago',
    description:
      'Overlooking the serene waters of Cheyenne Lake at The Broadmoor, Ristorante del Lago serves authentic Northern Italian cuisine in an intimate lakeside setting. Hand-rolled pastas, fresh-caught fish, wood-fired dishes, and an extensive Italian wine list make this one of Colorado Springs\' most romantic dining destinations.',
    shortDescription:
      'Authentic Northern Italian cuisine in an intimate lakeside setting at The Broadmoor.',
    category: 'fine-dining',
    cuisine: 'italian',
    neighborhood: 'broadmoor',
    address: '1 Lake Ave, Colorado Springs, CO 80906',
    phone: '7196347711',
    website: 'https://www.broadmoor.com/dining/ristorante-del-lago',
    priceRange: 4,
    hours: 'Tue–Sun 6:00 PM – 9:30 PM',
    features: JSON.stringify({ reservations: true, lakeViews: true, romanticDining: true }),
    featured: true,
    active: true,
    tier: 'free',
    displayOrder: 3,
  },
  {
    id: 4,
    name: "Shuga's Social House",
    slug: 'shugas-social-house',
    description:
      "Shuga's Social House is a beloved downtown Colorado Springs institution housed in a vibrant, eclectic space that blends art, music, and outstanding food. Known for its globally inspired American menu, creative cocktails, and warm community atmosphere, Shuga's is the kind of place where chefs, artists, and regulars all feel at home. The patio is one of downtown's best for warm evenings.",
    shortDescription:
      "Downtown's eclectic gathering spot serving globally inspired American cuisine with a legendary patio.",
    category: 'fine-dining',
    cuisine: 'american',
    neighborhood: 'downtown',
    address: '702 S Cascade Ave, Colorado Springs, CO 80903',
    phone: '7194481600',
    website: 'https://www.shugascafe.com',
    priceRange: 3,
    hours: 'Tue–Thu 11:00 AM – 9:00 PM | Fri–Sat 11:00 AM – 10:00 PM | Sun 10:00 AM – 3:00 PM',
    features: JSON.stringify({ patio: true, vegetarianOptions: true, liveMusic: true }),
    featured: true,
    active: true,
    tier: 'free',
    displayOrder: 4,
  },
  {
    id: 5,
    name: 'Craftwood Inn',
    slug: 'craftwood-inn',
    description:
      "Nestled in a 1920s English Tudor Arts & Crafts building in the heart of Manitou Springs, the Craftwood Inn is a Colorado dining landmark. The menu celebrates Colorado\'s bounty with elk, buffalo, venison, and fresh Rocky Mountain trout. Floor-to-ceiling windows frame stunning views of Pikes Peak, making it a favorite for special occasions and anniversaries.",
    shortDescription:
      'Historic 1920s inn serving Colorado game and Rocky Mountain cuisine with stunning Pikes Peak views.',
    category: 'fine-dining',
    cuisine: 'american',
    neighborhood: 'manitou-springs',
    address: '404 El Paso Blvd, Manitou Springs, CO 80829',
    phone: '7196858010',
    website: 'https://www.craftwood.com',
    priceRange: 3,
    hours: 'Mon–Sun 5:00 PM – 9:00 PM',
    features: JSON.stringify({ views: true, reservations: true, specialOccasion: true, coloradoGame: true }),
    featured: true,
    active: true,
    tier: 'free',
    displayOrder: 5,
  },
  {
    id: 6,
    name: 'The Famous Steakhouse',
    slug: 'the-famous-steakhouse',
    description:
      "A Colorado Springs institution since 1959, The Famous Steakhouse is the city's most historic fine dining destination. Located in a striking art deco building downtown, this storied restaurant has served prime steaks, fresh seafood, and classic American dishes to locals and visitors for over six decades. The Famous is beloved for its old-school elegance and consistently excellent food.",
    shortDescription:
      "Colorado Springs' most storied steakhouse, serving prime cuts and classic American fare since 1959.",
    category: 'fine-dining',
    cuisine: 'american',
    neighborhood: 'downtown',
    address: '31 N Tejon St, Colorado Springs, CO 80903',
    phone: '7196327212',
    website: 'https://www.thefamoussteakhouse.net',
    priceRange: 4,
    hours: 'Mon–Sat 4:00 PM – 10:00 PM | Sun 4:00 PM – 9:00 PM',
    features: JSON.stringify({ historic: true, reservations: true, privatedining: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 6,
  },

  // ── BREWERIES ──────────────────────────────────────────────────────
  {
    id: 7,
    name: 'Bristol Brewing Company',
    slug: 'bristol-brewing-company',
    description:
      "Bristol Brewing Company is a Colorado Springs institution, brewing award-winning craft beers since 1994. Located in the historic Ivywild School building — a renovated 1916 elementary school — Bristol offers a unique taproom experience with a bookstore, coffee shop, and community gathering spaces all under one roof. Favorites include Laughing Lab Scottish Ale and Mass Transit Ale. Dog-friendly patio is open year-round.",
    shortDescription:
      'Award-winning Colorado craft brewery in the historic Ivywild School, brewing since 1994.',
    category: 'brewery',
    cuisine: 'american',
    neighborhood: 'east-colorado-springs',
    address: '1604 S Cascade Ave, Colorado Springs, CO 80905',
    phone: '7196330086',
    website: 'https://www.bristolbrewing.com',
    priceRange: 2,
    hours: 'Mon–Thu 11:00 AM – 9:00 PM | Fri–Sat 11:00 AM – 10:00 PM | Sun 11:00 AM – 8:00 PM',
    features: JSON.stringify({ patio: true, dogFriendly: true, liveMusic: true, familyFriendly: true }),
    featured: true,
    active: true,
    tier: 'free',
    displayOrder: 7,
  },
  {
    id: 8,
    name: 'Phantom Canyon Brewing Co',
    slug: 'phantom-canyon-brewing-co',
    description:
      "Phantom Canyon Brewing Co has been a downtown Colorado Springs anchor since 1993, housed in a beautifully restored four-story 1901 brick building. With 12+ house-brewed beers on tap at all times, a full pub menu, a rooftop bar, and one of downtown's most coveted patios, Phantom Canyon is the quintessential Colorado Springs craft beer destination. The happy hour deals and live music schedule make it a regular stop for locals.",
    shortDescription:
      "Downtown's beloved craft brewery in a stunning 1901 building with a rooftop bar and legendary happy hours.",
    category: 'brewery',
    cuisine: 'american',
    neighborhood: 'downtown',
    address: '2 E Pikes Peak Ave, Colorado Springs, CO 80903',
    phone: '7196356000',
    website: 'https://www.phantomcanyon.com',
    priceRange: 2,
    hours: 'Mon–Thu 11:00 AM – 10:00 PM | Fri–Sat 11:00 AM – 11:00 PM | Sun 11:00 AM – 9:00 PM',
    features: JSON.stringify({ patio: true, happyHour: true, liveMusic: true, rooftopBar: true }),
    featured: true,
    active: true,
    tier: 'free',
    displayOrder: 8,
  },
  {
    id: 9,
    name: 'Cerberus Brewing Company',
    slug: 'cerberus-brewing-company',
    description:
      "Cerberus Brewing Company delivers bold, creative craft beers with a mythology-inspired approach to brewing. With a rotating tap list of 20+ beers — from hazy IPAs to dark stouts — and a food-truck-style kitchen menu, Cerberus has quickly become a north Colorado Springs favorite. The spacious taproom and adjoining patio host regular events, trivia nights, and live music.",
    shortDescription:
      'Bold, mythology-inspired craft brewery in north Colorado Springs with 20+ rotating taps.',
    category: 'brewery',
    cuisine: 'american',
    neighborhood: 'north-colorado-springs',
    address: '702 W Colorado Ave, Colorado Springs, CO 80905',
    phone: '7193281570',
    website: 'https://www.cerberusbrewing.com',
    priceRange: 2,
    hours: 'Mon–Thu 3:00 PM – 9:00 PM | Fri 2:00 PM – 10:00 PM | Sat 12:00 PM – 10:00 PM | Sun 12:00 PM – 8:00 PM',
    features: JSON.stringify({ patio: true, liveMusic: true, triviaNights: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 9,
  },
  {
    id: 10,
    name: 'Trinity Brewing Company',
    slug: 'trinity-brewing-company',
    description:
      "Trinity Brewing Company is known for pushing the boundaries of craft brewing with wild ales, sour beers, and barrel-aged creations. A Certified B Corporation and LOCUS-certified brewer, Trinity is as committed to sustainability as it is to flavor. Their Belgian-inspired farmhouse ales and innovative experimental batches have earned national recognition. The cozy taproom along Academy Boulevard attracts serious beer enthusiasts.",
    shortDescription:
      'Nationally recognized for wild ales and sours, Trinity is Colorado Springs\' most experimental brewery.',
    category: 'brewery',
    cuisine: 'american',
    neighborhood: 'academy-blvd',
    address: '1466 Garden of the Gods Rd, Colorado Springs, CO 80907',
    phone: '7196347998',
    website: 'https://www.trinitybrew.com',
    priceRange: 2,
    hours: 'Tue–Thu 3:00 PM – 9:00 PM | Fri 2:00 PM – 10:00 PM | Sat 12:00 PM – 10:00 PM | Sun 12:00 PM – 8:00 PM',
    features: JSON.stringify({ wildAles: true, sustainable: true, dogFriendly: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 10,
  },
  {
    id: 11,
    name: 'Goat Patch Brewing Company',
    slug: 'goat-patch-brewing-company',
    description:
      "Goat Patch Brewing Company is a woman-owned craft brewery serving approachable, high-quality beers in a welcoming, community-focused taproom. From their flagship Colorado Common Lager to seasonal IPAs and nitro stouts, Goat Patch balances classic styles with local creativity. Regular food trucks, yoga sessions, and community events make it a neighborhood hub.",
    shortDescription:
      'Woman-owned craft brewery with approachable beers and a vibrant community taproom.',
    category: 'brewery',
    cuisine: 'american',
    neighborhood: 'academy-blvd',
    address: '2727 N Cascade Ave, Colorado Springs, CO 80907',
    phone: '7193280681',
    website: 'https://www.goatpatchbrewing.com',
    priceRange: 2,
    hours: 'Mon–Thu 3:00 PM – 9:00 PM | Fri 12:00 PM – 10:00 PM | Sat 11:00 AM – 10:00 PM | Sun 11:00 AM – 8:00 PM',
    features: JSON.stringify({ dogFriendly: true, familyFriendly: true, foodTrucks: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 11,
  },
  {
    id: 12,
    name: 'Pikes Peak Brewing Company',
    slug: 'pikes-peak-brewing-company',
    description:
      "Pikes Peak Brewing Company in Monument (just north of Colorado Springs) is a must-visit for fans of well-crafted, classic-style ales and lagers. Named after the iconic 14er that defines the Front Range skyline, this brewery focuses on quality and consistency. Their Summit House IPA and Crystal Peak Pale Ale are perennial local favorites. The large, family-friendly taproom is ideal for groups.",
    shortDescription:
      'Monument craft brewery honoring Pikes Peak with classic, well-crafted ales and lagers.',
    category: 'brewery',
    cuisine: 'american',
    neighborhood: 'east-colorado-springs',
    address: '1545 Tuskegee Pl, Colorado Springs, CO 80915',
    phone: '7195314759',
    website: 'https://www.pikespeakbrewing.com',
    priceRange: 2,
    hours: 'Mon–Thu 3:00 PM – 9:00 PM | Fri 1:00 PM – 10:00 PM | Sat 11:00 AM – 10:00 PM | Sun 11:00 AM – 8:00 PM',
    features: JSON.stringify({ familyFriendly: true, dogFriendly: true, patio: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 12,
  },
  {
    id: 13,
    name: 'Red Leg Brewing Company',
    slug: 'red-leg-brewing-company',
    description:
      "Red Leg Brewing Company is a military-themed craft brewery honoring the soldiers of Fort Carson and the U.S. Army. Each of their beers is named and styled in tribute to military history, from the Howitzer Hefeweizen to the Reconnaissance IPA. Located in a spacious taproom on the east side of Colorado Springs, Red Leg draws a loyal crowd of veterans, active military, and craft beer fans alike.",
    shortDescription:
      'Military-themed craft brewery honoring Fort Carson soldiers with patriotic brews and community pride.',
    category: 'brewery',
    cuisine: 'american',
    neighborhood: 'east-colorado-springs',
    address: '4630 Forge Rd, Colorado Springs, CO 80907',
    phone: '7192717889',
    website: 'https://www.redlegbrewing.com',
    priceRange: 2,
    hours: 'Mon–Thu 2:00 PM – 9:00 PM | Fri 12:00 PM – 10:00 PM | Sat 11:00 AM – 10:00 PM | Sun 11:00 AM – 8:00 PM',
    features: JSON.stringify({ militaryFriendly: true, patio: true, dogFriendly: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 13,
  },
  {
    id: 14,
    name: 'Metric Brewing',
    slug: 'metric-brewing',
    description:
      "Metric Brewing brings a fresh, design-forward aesthetic to the Colorado Springs craft beer scene. Their downtown taproom is a visual delight with rotating art installations and a sleek minimalist interior. The beer program emphasizes bold West Coast IPAs, refreshing lagers, and creative seasonal releases. A rotating roster of food trucks keeps the full menu varied and interesting.",
    shortDescription:
      'Design-forward downtown brewery known for bold IPAs, rotating art, and creative seasonal releases.',
    category: 'brewery',
    cuisine: 'american',
    neighborhood: 'downtown',
    address: '831 Arcturus Dr, Colorado Springs, CO 80905',
    phone: '7193282468',
    website: 'https://www.metricbrewing.com',
    priceRange: 2,
    hours: 'Wed–Thu 3:00 PM – 9:00 PM | Fri 2:00 PM – 10:00 PM | Sat 12:00 PM – 10:00 PM | Sun 12:00 PM – 7:00 PM',
    features: JSON.stringify({ artEvents: true, foodTrucks: true, patio: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 14,
  },
  {
    id: 15,
    name: 'Gold Camp Brewing Company',
    slug: 'gold-camp-brewing-company',
    description:
      "Gold Camp Brewing Company is nestled in the heart of Old Colorado City, the historic arts district just west of downtown. Inspired by the gold rush history of the Pikes Peak region, Gold Camp brews approachable, flavorful beers that pair perfectly with the neighborhood's eclectic dining and gallery scene. Their covered patio is one of the most pleasant in the Old Colorado City area.",
    shortDescription:
      "Old Colorado City's neighborhood brewery, inspired by Pikes Peak gold rush history.",
    category: 'brewery',
    cuisine: 'american',
    neighborhood: 'old-colorado-city',
    address: '2625 W Colorado Ave, Colorado Springs, CO 80904',
    phone: '7193285180',
    website: 'https://www.goldcampbrewing.com',
    priceRange: 2,
    hours: 'Mon–Thu 3:00 PM – 9:00 PM | Fri 2:00 PM – 10:00 PM | Sat 12:00 PM – 10:00 PM | Sun 12:00 PM – 8:00 PM',
    features: JSON.stringify({ patio: true, dogFriendly: true, liveMusic: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 15,
  },

  // ── MEXICAN ───────────────────────────────────────────────────────
  {
    id: 16,
    name: "Senor Pepper's Mexican Grill",
    slug: 'senor-peppers-mexican-grill',
    description:
      "Senor Pepper's is a cherished Old Colorado City staple serving generous portions of authentic Mexican food in a festive, colorful atmosphere. Known for their hand-crafted margaritas, sizzling fajitas, and chile verde that rivals any in Colorado, this family-owned restaurant has been feeding the neighborhood for decades. The shaded patio along Colorado Avenue is perfect for summer dining.",
    shortDescription:
      "Old Colorado City's beloved Mexican grill with hand-crafted margaritas and legendary chile verde.",
    category: 'restaurant',
    cuisine: 'mexican',
    neighborhood: 'old-colorado-city',
    address: '2813 W Colorado Ave, Colorado Springs, CO 80904',
    phone: '7196320707',
    website: 'https://www.senorpeppers.com',
    priceRange: 2,
    hours: 'Mon–Thu 11:00 AM – 9:00 PM | Fri–Sat 11:00 AM – 10:00 PM | Sun 11:00 AM – 9:00 PM',
    features: JSON.stringify({ patio: true, margaritas: true, familyOwned: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 16,
  },
  {
    id: 17,
    name: 'La Casita Mexican Restaurant',
    slug: 'la-casita-mexican-restaurant',
    description:
      "La Casita is a downtown Colorado Springs institution that has been serving authentic, home-style Mexican food to the community for over 30 years. Family-owned and operated, La Casita delivers the kind of unpretentious, flavorful Mexican cooking you'd find in a family home south of the border. The enchiladas, tamales, and daily specials keep loyal customers returning week after week.",
    shortDescription:
      "Downtown institution serving authentic, home-style Mexican food for over 30 years.",
    category: 'restaurant',
    cuisine: 'mexican',
    neighborhood: 'downtown',
    address: '209 S Sierra Madre St, Colorado Springs, CO 80903',
    phone: '7196325401',
    website: '',
    priceRange: 1,
    hours: 'Mon–Sat 10:00 AM – 8:00 PM | Sun 11:00 AM – 7:00 PM',
    features: JSON.stringify({ familyOwned: true, authentic: true, affordable: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 17,
  },
  {
    id: 18,
    name: 'El Taco Rey',
    slug: 'el-taco-rey',
    description:
      "El Taco Rey is where Colorado Springs locals go for authentic, no-frills Mexican street food. The tacos — loaded with slow-cooked carne asada, al pastor, or carnitas — are among the best in the city. With counter service, affordable prices, and recipes straight from the Jalisco region, El Taco Rey is the undisputed king of value Mexican dining in Colorado Springs.",
    shortDescription:
      'No-frills counter-service tacos with authentic Jalisco-style meats at unbeatable prices.',
    category: 'restaurant',
    cuisine: 'mexican',
    neighborhood: 'south',
    address: '1060 S Tejon St, Colorado Springs, CO 80903',
    phone: '7196323330',
    website: '',
    priceRange: 1,
    hours: 'Mon–Sat 10:00 AM – 9:00 PM | Sun 10:00 AM – 8:00 PM',
    features: JSON.stringify({ authentic: true, affordable: true, quickService: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 18,
  },
  {
    id: 19,
    name: "Machete's House of Knives",
    slug: 'machetes-house-of-knives',
    description:
      "Machete's is a lively downtown Mexican restaurant and bar known for bold flavors, creative takes on classic dishes, and an electric atmosphere. From loaded street tacos and birria quesadillas to craft agave cocktails and local beer pairings, Machete's blends the spirit of a Mexico City cantina with a Colorado Springs neighborhood bar. Loud, fun, and unapologetically flavorful.",
    shortDescription:
      'Downtown Mexican cantina known for bold street tacos, birria, and craft agave cocktails.',
    category: 'restaurant',
    cuisine: 'mexican',
    neighborhood: 'downtown',
    address: '108 N Tejon St, Colorado Springs, CO 80903',
    phone: '7192169124',
    website: 'https://www.machetescafe.com',
    priceRange: 2,
    hours: 'Mon–Thu 11:00 AM – 9:00 PM | Fri–Sat 11:00 AM – 11:00 PM | Sun 11:00 AM – 8:00 PM',
    features: JSON.stringify({ liveMusic: true, happyHour: true, patio: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 19,
  },

  // ── ITALIAN ───────────────────────────────────────────────────────
  {
    id: 20,
    name: 'Pizzeria Rustica',
    slug: 'pizzeria-rustica',
    description:
      "Pizzeria Rustica serves artisan Neapolitan-style pizzas from a wood-fired oven in the heart of Old Colorado City. Owner-operated and intensely focused on quality, every pizza is made with imported Italian flour, San Marzano tomatoes, and house-made mozzarella. The patio is one of the most charming in the city, and the rotating selection of small-batch wines and Italian craft beers rounds out the experience.",
    shortDescription:
      "Old Colorado City's artisan Neapolitan pizza with wood-fired oven and a charming garden patio.",
    category: 'restaurant',
    cuisine: 'italian',
    neighborhood: 'old-colorado-city',
    address: '2527 W Colorado Ave, Colorado Springs, CO 80904',
    phone: '7196328121',
    website: 'https://www.pizzeriarustica.com',
    priceRange: 2,
    hours: 'Tue–Sun 5:00 PM – 9:00 PM',
    features: JSON.stringify({ patio: true, woodFired: true, vegetarianOptions: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 20,
  },
  {
    id: 21,
    name: 'Cucina Colore',
    slug: 'cucina-colore',
    description:
      "Cucina Colore is a cozy downtown Italian bistro delivering the flavors of Northern Italy through handmade pastas, seasonal risottos, and classic secondi plates. The intimate dining room with its warm lighting and Italian countryside decor creates a romantic atmosphere perfect for date nights. An extensive Italian wine list and house-made desserts complete the experience.",
    shortDescription:
      'Intimate downtown Italian bistro with handmade pastas and an extensive Italian wine list.',
    category: 'restaurant',
    cuisine: 'italian',
    neighborhood: 'downtown',
    address: '301 E Platte Ave, Colorado Springs, CO 80903',
    phone: '7196342222',
    website: '',
    priceRange: 3,
    hours: 'Tue–Thu 5:00 PM – 9:00 PM | Fri–Sat 5:00 PM – 10:00 PM',
    features: JSON.stringify({ reservations: true, romanticDining: true, wineDining: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 21,
  },

  // ── AMERICAN / CASUAL ─────────────────────────────────────────────
  {
    id: 22,
    name: 'Cowboys',
    slug: 'cowboys-colorado-springs',
    description:
      "Cowboys is a Colorado Springs nightlife staple, combining a full-service restaurant, bar, and entertainment venue in one sprawling downtown space. Known for their generously portioned American comfort food, extensive beer selection, and nightly live country and rock music, Cowboys draws a lively crowd seven days a week. The large outdoor patio with fire pits is a popular gathering spot during cooler Colorado evenings.",
    shortDescription:
      'Downtown entertainment hub with American comfort food, live music nightly, and a fire-pit patio.',
    category: 'bar',
    cuisine: 'american',
    neighborhood: 'downtown',
    address: '3910 N Nevada Ave, Colorado Springs, CO 80907',
    phone: '7192600022',
    website: 'https://www.cowboyscoloradosprings.com',
    priceRange: 2,
    hours: 'Mon–Fri 4:00 PM – 2:00 AM | Sat–Sun 12:00 PM – 2:00 AM',
    features: JSON.stringify({ liveMusic: true, patio: true, happyHour: true, dancing: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 22,
  },
  {
    id: 23,
    name: 'Jack Quinn Irish Pub',
    slug: 'jack-quinn-irish-pub',
    description:
      "Jack Quinn Irish Pub & Restaurant is the quintessential Irish pub experience transplanted to the heart of downtown Colorado Springs. Authentic Irish fare — shepherd's pie, fish and chips, Guinness beef stew — pairs perfectly with the extensive whiskey selection and 20 beers on draft. The warm, welcoming atmosphere, weekend live Celtic and folk music, and legendary happy hours have made Jack Quinn's a downtown institution.",
    shortDescription:
      "Downtown's authentic Irish pub with legendary happy hours, live Celtic music, and exceptional whiskey.",
    category: 'bar',
    cuisine: 'irish',
    neighborhood: 'downtown',
    address: '21 S Tejon St, Colorado Springs, CO 80903',
    phone: '7193856544',
    website: 'https://www.jackquinns.com',
    priceRange: 2,
    hours: 'Mon–Fri 11:00 AM – 2:00 AM | Sat–Sun 10:00 AM – 2:00 AM',
    features: JSON.stringify({ patio: true, happyHour: true, liveMusic: true, whiskey: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 23,
  },
  {
    id: 24,
    name: 'Edelweiss Restaurant',
    slug: 'edelweiss-restaurant',
    description:
      "A delightful anomaly in the Colorado Springs dining scene, Edelweiss has been serving authentic German cuisine since 1961. Tucked into the charming streets of Old Colorado City, this family-owned restaurant serves traditional Bavarian specialties — schnitzel, sauerbraten, bratwurst, and house-made strudel — alongside an impressive selection of German beers and wines. The polka nights and festive Oktoberfest celebrations are legendary.",
    shortDescription:
      'Authentic German Bavarian cuisine in Old Colorado City, serving since 1961 with polka nights and Oktoberfest.',
    category: 'restaurant',
    cuisine: 'german',
    neighborhood: 'old-colorado-city',
    address: '34 E Ramona Ave, Colorado Springs, CO 80903',
    phone: '7196345771',
    website: 'https://www.edelweissrestaurant.com',
    priceRange: 3,
    hours: 'Tue–Sun 5:00 PM – 9:00 PM',
    features: JSON.stringify({ unique: true, historic: true, liveMusic: true, reservations: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 24,
  },
  {
    id: 25,
    name: "King's Chef Diner",
    slug: 'kings-chef-diner',
    description:
      "King's Chef Diner is a beloved Colorado Springs breakfast and lunch institution operating since the 1950s. A true American greasy spoon in the best possible sense, King's Chef is famous for its green chile — poured generously over burritos, eggs, and hash browns. The lunch counter atmosphere, friendly staff, and outrageously affordable prices have made it a must-visit for anyone who wants to eat like a local.",
    shortDescription:
      "A 1950s Colorado Springs breakfast institution famous for its legendary green chile and affordable prices.",
    category: 'restaurant',
    cuisine: 'american',
    neighborhood: 'downtown',
    address: '110 E Costilla St, Colorado Springs, CO 80903',
    phone: '7196326135',
    website: '',
    priceRange: 1,
    hours: 'Mon–Sat 6:00 AM – 2:00 PM | Sun 7:00 AM – 2:00 PM',
    features: JSON.stringify({ breakfast: true, affordable: true, historic: true, greenChile: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 25,
  },

  // ── BBQ ───────────────────────────────────────────────────────────
  {
    id: 26,
    name: 'Sugarfire Smoke House',
    slug: 'sugarfire-smoke-house',
    description:
      "Sugarfire Smoke House brings St. Louis-style BBQ excellence to Colorado Springs. Slow-smoked brisket, pulled pork, St. Louis ribs, and smoked chicken are all served by the pound or on loaded sandwiches with house-made sides. The open-kitchen smoke pit fills the restaurant with an irresistible aroma. Sugarfire has earned national acclaim and a devoted local following for its no-compromise approach to real barbecue.",
    shortDescription:
      "National award-winning St. Louis-style BBQ with slow-smoked brisket, ribs, and loaded sandwiches.",
    category: 'restaurant',
    cuisine: 'bbq',
    neighborhood: 'north-colorado-springs',
    address: '1750 Hollowbrook Dr, Colorado Springs, CO 80918',
    phone: '7192601800',
    website: 'https://www.sugarfiresmokehouse.com',
    priceRange: 2,
    hours: 'Sun–Thu 11:00 AM – 9:00 PM | Fri–Sat 11:00 AM – 10:00 PM',
    features: JSON.stringify({ smokehouse: true, familyFriendly: true, catering: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 26,
  },
  {
    id: 27,
    name: 'Brother Luck Street Eats',
    slug: 'brother-luck-street-eats',
    description:
      "Brother Luck Street Eats is downtown Colorado Springs' most celebrated farm-to-table restaurant, helmed by Top Chef alum Chef Brother Luck. The seasonally evolving menu draws inspiration from global street food traditions while championing Colorado farmers and producers. The restaurant is a catalyst for downtown dining culture, featuring an ever-changing tasting menu and an electric energy that makes every visit memorable.",
    shortDescription:
      'Downtown farm-to-table restaurant by Top Chef alum Brother Luck, celebrating Colorado ingredients.',
    category: 'restaurant',
    cuisine: 'american',
    neighborhood: 'downtown',
    address: '315 E Pikes Peak Ave, Colorado Springs, CO 80903',
    phone: '7199557510',
    website: 'https://www.brotherluckstreet.com',
    priceRange: 2,
    hours: 'Tue–Sat 11:00 AM – 9:00 PM',
    features: JSON.stringify({ farmToTable: true, seasonal: true, reservations: true }),
    featured: true,
    active: true,
    tier: 'free',
    displayOrder: 27,
  },

  // ── COFFEE / CAFES ────────────────────────────────────────────────
  {
    id: 28,
    name: 'Loyal Coffee',
    slug: 'loyal-coffee',
    description:
      "Loyal Coffee is Colorado Springs' premier specialty coffee destination, known for meticulous sourcing, precision brewing, and a deeply knowledgeable barista team. Located in a sleek, minimalist downtown space, Loyal offers single-origin pour-overs, espresso drinks made with rotating micro-lot coffees, and a curated selection of pastries. Coffee lovers will find depth and intentionality in every cup.",
    shortDescription:
      "Colorado Springs' premier specialty coffee bar with single-origin pour-overs and precision espresso.",
    category: 'cafe',
    cuisine: 'other',
    neighborhood: 'downtown',
    address: '410 N Tejon St, Colorado Springs, CO 80903',
    phone: '7193281625',
    website: 'https://www.loyalcoffee.com',
    priceRange: 1,
    hours: 'Mon–Fri 6:30 AM – 5:00 PM | Sat–Sun 7:00 AM – 5:00 PM',
    features: JSON.stringify({ specialty: true, wifi: true, laptop: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 28,
  },
  {
    id: 29,
    name: 'Story Coffee Company',
    slug: 'story-coffee-company',
    description:
      "Story Coffee Company is a warm, welcoming specialty cafe in downtown Colorado Springs that takes its name seriously — every cup tells a story of the farmer, the origin, and the craft. With direct-trade sourcing, house-roasted beans, and a beautifully designed neighborhood cafe, Story has become a morning ritual for downtown residents and a discovery destination for visitors seeking great coffee.",
    shortDescription:
      'Direct-trade specialty cafe with house-roasted beans and a beautifully designed downtown space.',
    category: 'cafe',
    cuisine: 'other',
    neighborhood: 'downtown',
    address: '507 N Tejon St, Colorado Springs, CO 80903',
    phone: '7194714144',
    website: 'https://www.storycoffeeco.com',
    priceRange: 1,
    hours: 'Mon–Sat 7:00 AM – 6:00 PM | Sun 8:00 AM – 5:00 PM',
    features: JSON.stringify({ specialty: true, wifi: true, directTrade: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 29,
  },
  {
    id: 30,
    name: 'Pikes Peak Coffee House',
    slug: 'pikes-peak-coffee-house',
    description:
      "Pikes Peak Coffee House is a charming neighborhood cafe near the Broadmoor, serving expertly crafted espresso drinks, signature blended beverages, and freshly baked pastries. With a cozy interior, quick and friendly service, and views of the mountains from the outdoor seating area, this is the kind of neighborhood cafe that regulars would never want to lose.",
    shortDescription:
      "Charming Broadmoor-area neighborhood cafe with expertly crafted espresso and mountain-view seating.",
    category: 'cafe',
    cuisine: 'other',
    neighborhood: 'broadmoor',
    address: '2516 W Colorado Ave, Colorado Springs, CO 80904',
    phone: '7196329600',
    website: '',
    priceRange: 1,
    hours: 'Mon–Fri 6:00 AM – 5:00 PM | Sat–Sun 7:00 AM – 4:00 PM',
    features: JSON.stringify({ patio: true, breakfast: true, quickService: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 30,
  },
  {
    id: 31,
    name: 'Two Rivers Craft Coffee',
    slug: 'two-rivers-craft-coffee',
    description:
      "Two Rivers Craft Coffee is a beloved Old Colorado City cafe with a passionate commitment to craft. Using ethically sourced beans roasted locally, they create espresso drinks, cold brews, and seasonal lattes that feel both artisanal and approachable. The cozy, art-lined interior reflects the creative spirit of Old Colorado City's gallery and arts district.",
    shortDescription:
      "Old Colorado City's craft coffee gem with ethically sourced beans and art-lined cozy interiors.",
    category: 'cafe',
    cuisine: 'other',
    neighborhood: 'old-colorado-city',
    address: '2614 W Colorado Ave, Colorado Springs, CO 80904',
    phone: '7196322490',
    website: '',
    priceRange: 1,
    hours: 'Mon–Fri 6:30 AM – 4:00 PM | Sat–Sun 7:00 AM – 4:00 PM',
    features: JSON.stringify({ artsy: true, cozy: true, wifi: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 31,
  },

  // ── ASIAN ─────────────────────────────────────────────────────────
  {
    id: 32,
    name: 'Bangkok Cuisine',
    slug: 'bangkok-cuisine',
    description:
      "Bangkok Cuisine is consistently rated among the best Thai restaurants in Colorado Springs. The menu spans the full breadth of Thai cooking — from fragrant curries and tom kha soup to pad see ew and mango sticky rice — all prepared with authentic ingredients and genuine skill. Reasonable prices, generous portions, and warm hospitality keep the dining room reliably busy.",
    shortDescription:
      "Colorado Springs' top-rated Thai restaurant with fragrant curries and authentic flavors.",
    category: 'restaurant',
    cuisine: 'thai',
    neighborhood: 'downtown',
    address: '1108 S Nevada Ave, Colorado Springs, CO 80903',
    phone: '7196346788',
    website: 'https://www.bangkokcuisine.net',
    priceRange: 2,
    hours: 'Mon–Thu 11:00 AM – 9:00 PM | Fri–Sat 11:00 AM – 10:00 PM | Sun 12:00 PM – 9:00 PM',
    features: JSON.stringify({ vegetarianOptions: true, veganOptions: true, glutenFree: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 32,
  },
  {
    id: 33,
    name: "La'au's Taco Shop",
    slug: 'laaus-taco-shop',
    description:
      "La'au's Taco Shop is a unique and addictive counter-service spot bringing Hawaiian-Mexican fusion to downtown Colorado Springs. Their famous kalua pork tacos, Korean BBQ burritos, and loco moco bowls have developed a passionate following. Bright flavors, fresh ingredients, and a playful spirit make La'au's one of the most original dining experiences in the city.",
    shortDescription:
      "Unique Hawaiian-Mexican fusion with addictive kalua pork tacos and Korean BBQ burritos.",
    category: 'restaurant',
    cuisine: 'asian',
    neighborhood: 'downtown',
    address: '830 N Tejon St, Colorado Springs, CO 80903',
    phone: '7194718226',
    website: 'https://www.laaustacoshop.com',
    priceRange: 1,
    hours: 'Mon–Sat 11:00 AM – 8:00 PM | Sun 12:00 PM – 7:00 PM',
    features: JSON.stringify({ unique: true, affordable: true, fusion: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 33,
  },

  // ── FOOD TRUCKS ───────────────────────────────────────────────────
  {
    id: 34,
    name: 'Colorado Springs Food Truck Scene',
    slug: 'colorado-springs-food-trucks',
    description:
      "Colorado Springs has a thriving food truck culture, with dozens of rotating vendors serving everything from gourmet tacos and Hawaiian plates to wood-fired pizza and Korean BBQ. Check local brewery taprooms — Bristol, Goat Patch, Cerberus — for scheduled food truck nights. The Downtown Food Truck Rally on summer Fridays at Acacia Park is a local institution, drawing 10–15 trucks each week.",
    shortDescription:
      "Colorado Springs' vibrant food truck scene, from brewery lots to summer downtown rallies.",
    category: 'food-truck',
    cuisine: 'american',
    neighborhood: 'downtown',
    address: 'Acacia Park, 115 E Platte Ave, Colorado Springs, CO 80903',
    phone: '',
    website: '',
    priceRange: 1,
    hours: 'Fri 11:00 AM – 2:00 PM (Downtown Rally, seasonal)',
    features: JSON.stringify({ seasonal: true, outdoor: true, dogFriendly: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 34,
  },

  // ── BAR / PATIO ───────────────────────────────────────────────────
  {
    id: 35,
    name: 'The Rabbit Hole',
    slug: 'the-rabbit-hole',
    description:
      "The Rabbit Hole is a subterranean cocktail bar and restaurant hidden beneath downtown Colorado Springs, offering an imaginative experience inspired by Alice in Wonderland. The craft cocktail program is among the most creative in the city, featuring house-infused spirits, culinary garnishes, and rotating seasonal menus. The intimate, dimly lit space is ideal for date nights and special celebrations.",
    shortDescription:
      "Subterranean cocktail bar with imaginative Alice in Wonderland-inspired drinks and creative dining.",
    category: 'bar',
    cuisine: 'american',
    neighborhood: 'downtown',
    address: '101 N Tejon St, Colorado Springs, CO 80903',
    phone: '7196358434',
    website: 'https://www.therabbitholecs.com',
    priceRange: 3,
    hours: 'Tue–Thu 4:00 PM – 10:00 PM | Fri–Sat 4:00 PM – 12:00 AM | Sun 4:00 PM – 9:00 PM',
    features: JSON.stringify({ cocktails: true, unique: true, reservations: true, romanticDining: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 35,
  },
  {
    id: 36,
    name: 'Front Range Barbeque',
    slug: 'front-range-barbeque',
    description:
      "Front Range Barbeque is a casual, counter-service barbecue spot in Old Colorado City beloved for its slow-smoked meats and classic BBQ sides. Brisket, pulled pork, and ribs are all smoked low and slow over local hardwood. The laid-back atmosphere, reasonable prices, and picnic-table seating make it a perfect casual lunch or dinner spot for families and groups.",
    shortDescription:
      "Old Colorado City counter-service BBQ with slow-smoked brisket, pulled pork, and classic sides.",
    category: 'restaurant',
    cuisine: 'bbq',
    neighborhood: 'old-colorado-city',
    address: '2330 W Colorado Ave, Colorado Springs, CO 80904',
    phone: '7196328081',
    website: '',
    priceRange: 2,
    hours: 'Tue–Sat 11:00 AM – 8:00 PM | Sun 11:00 AM – 6:00 PM',
    features: JSON.stringify({ smokehouse: true, familyFriendly: true, patio: true }),
    featured: false,
    active: true,
    tier: 'free',
    displayOrder: 36,
  },
]
